server:
  port: 80
spring:
  application:
    name: chat-demo
  datasource:
    url: jdbc:sqlite:chat.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: false
  swagger:
    enabled: true
    title: 微信GPT
    contact:
      name: xu.zhao
      email: 458114067@qq.com
      url: http://localhost//swagger-ui.html
    security:
      # 是否启用 swagger 登录验证
      filter-plugin: true
      username: zhao458114067
      password: zhaoxujiayou
  profiles:
    active: prod

we-chat:
  # 微信测试公众号，官方提供
  secret: e63fae26xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  app-id: wx79dfxxxxxxxxxxxx
  # 自己设置的token
  token: zhaoxujiayou
  encoding-aes-key: ysUobI3Wgxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # 自己的素材
  media-id: JZs7V6OoFigpG4ZxBZ6jNF-WVnz2fcq4mxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # 订阅消息
  subscribe-message:
    template:
      prediction-id: poz--THhGi0VrnXKxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # 模板消息
  template:
    warning-id: sghchOqWytTjRBSDxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# 天气key
console:
  weather:
    key: e97eexxxxxxxxxxxxxxxxxxxxxxxxxxxx
chat-gpt:
  api:
    # chatGpt官网申请的key，可以是多个
    keys:
      - sk-MgduMlIciGiFxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - sk-cIBxidl6RnrQxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - sk-106wM44zegokxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - sk-KSYg4dxQH0oxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - sk-WRwDaJ463DZxxxxxxxxxxxxxxxxxxxxxxxxxxxx